name: Windows CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: windows-latest
    strategy:
      fail-fast: false

      matrix:
        build_type:
          - Release
          - Debug

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Boost
      run: choco install boost-msvc-14.1

    - name: Install ASIO standalone
      run: |
        curl -L -o asio.zip https://github.com/chriskohlhoff/asio/archive/refs/tags/asio-1-18-2.zip
        tar -xf asio.zip
        move asio-asio-1-18-2 asio

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -DASIO_INCLUDEDIR=${{ github.workspace }}/asio/asio/include -DCLI_BuildTests=ON -DCLI_BuildExamples=ON -DCLI_UseBoostAsio=ON

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Run tests
      # working-directory: build
      working-directory: build/test/${{matrix.build_type}}
      # run: ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure --verbose
      run: ./test_suite -l all
