name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Boost
      run: choco install boost-msvc-14.1

    - name: Install ASIO standalone
      run: |
        curl -L -o asio.zip https://github.com/chriskohlhoff/asio/archive/refs/tags/asio-1-18-2.zip
        tar -xf asio.zip
        move asio-asio-1-18-2 asio

    - name: Configure CMake
      run: cmake -S . -B build -DASIO_INCLUDEDIR=${GITHUB_WORKSPACE}/asio/asio/include -DCLI_BuildTests=ON -DCLI_BuildExamples=ON -DCLI_UseBoostAsio=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
